import '@/styles/globals.css';
import 'antd/dist/reset.css'; // Import Ant Design styles
import { ToastContainer } from "react-toastify";
import { getCspNonce } from "@/lib/getNonce";
import { Nunito, Plus_Jakarta_Sans, Inter } from 'next/font/google';
import Script from 'next/script';

// Nunito — used for all headings (h1-h6), matches UAT bold rounded style
const nunito = Nunito({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
  variable: '--font-nunito',
  display: 'swap',
});

// Plus Jakarta Sans — used for body text, paragraphs, labels
const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
  variable: '--font-plus-jakarta-sans',
  display: 'swap',
});

// Inter — used for UI elements (tables, inputs, data)
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

export const metadata = {
  title: 'My Health Passport',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
  icons: [{ rel: 'icon', type: 'image/png', sizes: '32x32', url: '/icon.png' }],
  verification: {
    google: 'TCzuIWNOHD4mIqmt9BdqOz5pnjYFM_nbTYGLqf0WjRU',
  },
};

export default async function RootLayout({ children }) {
  const nonce = await getCspNonce();

  return (
    <html lang="en" className={`${nunito.variable} ${plusJakartaSans.variable} ${inter.variable}`}>
      <head nonce={nonce}></head>
      <body className="h-full">
        {/* Google Analytics */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-H7VTQ1BJ10"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-H7VTQ1BJ10');
          `}
        </Script>
        {/* Facebook Pixel */}
        <Script id="facebook-pixel" strategy="afterInteractive">
          {`
            !function(f,b,e,v,n,t,s)
            {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
            n.callMethod.apply(n,arguments):n.queue.push(arguments)};
            if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
            n.queue=[];t=b.createElement(e);t.async=!0;
            t.src=v;s=b.getElementsByTagName(e)[0];
            s.parentNode.insertBefore(t,s)}(window,document,'script',
            'https://connect.facebook.net/en_US/fbevents.js');
            fbq('init', '3278865192300983');
            fbq('track', 'PageView');
          `}
        </Script>
        <noscript>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img height="1" width="1" style={{display:'none'}}
            src="https://www.facebook.com/tr?id=3278865192300983&ev=PageView&noscript=1"
            alt=""
          />
        </noscript>
        {children}
        {/* <NextTopLoader /> */}
        <ToastContainer />
      </body>
    </html>
  );
}
