import '@/styles/globals.css';
import 'antd/dist/reset.css'; // Import Ant Design styles
import { ToastContainer } from "react-toastify";
import { getCspNonce } from "@/lib/getNonce";

export const metadata = {
  title: 'My Health Passport',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
  icons: [{ rel: 'icon', type: 'image/png', sizes: '32x32', url: '/icon.png' }],
};

export default async function RootLayout({ children }) {
  const nonce = await getCspNonce();

  return (
    <html lang="en">
      <head nonce={nonce}></head>
      <body className="h-full" >
        {children}
        {/* <NextTopLoader /> */}
        <ToastContainer />
      </body>
    </html >
  );
}
