from tortoise import BaseDBAsyncClient


async def upgrade(db: BaseDBAsyncClient) -> str:
    return """
        CREATE TABLE IF NOT EXISTS "admin_users" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "first_name" VARCHAR(50) NOT NULL DEFAULT '',
    "last_name" VARCHAR(50) NOT NULL DEFAULT '',
    "middle_name" VARCHAR(50) NOT NULL DEFAULT '',
    "username" VARCHAR(50) NOT NULL UNIQUE,
    "phone" VARCHAR(20) NOT NULL UNIQUE,
    "email" VARCHAR(100) DEFAULT '',
    "password" TEXT,
    "is_active" BOOL NOT NULL DEFAULT True,
    "is_verified" BOOL NOT NULL DEFAULT True,
    "profile_image" VARCHAR(255) NOT NULL DEFAULT '',
    "user_role" VARCHAR(19) NOT NULL DEFAULT 'PROGRAM_COORDINATOR',
    "role_type" VARCHAR(50) NOT NULL DEFAULT 'ADMIN_TEAM',
    "dob" DATE,
    "gender" VARCHAR(20) NOT NULL DEFAULT '',
    "address_line_1" VARCHAR(100) NOT NULL DEFAULT '',
    "address_line_2" VARCHAR(100) NOT NULL DEFAULT '',
    "landmark" VARCHAR(100) NOT NULL DEFAULT '',
    "street_name" VARCHAR(100) NOT NULL DEFAULT '',
    "state" VARCHAR(50) NOT NULL DEFAULT '',
    "pincode" VARCHAR(10) NOT NULL DEFAULT '',
    "country_calling_code" VARCHAR(5) NOT NULL DEFAULT '',
    "country" VARCHAR(50) NOT NULL DEFAULT '',
    "location" VARCHAR(50) NOT NULL DEFAULT '',
    "blood_group" VARCHAR(10) DEFAULT '',
    "spoken_languages" TEXT,
    "days_available" TEXT,
    "employee_id" VARCHAR(50) UNIQUE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "created_user_role" VARCHAR(50) DEFAULT '',
    "created_role_type" VARCHAR(50) DEFAULT '',
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_user_role" VARCHAR(50) DEFAULT '',
    "updated_role_type" VARCHAR(50) DEFAULT '',
    "deleted_at" TIMESTAMPTZ,
    "is_deleted" BOOL NOT NULL DEFAULT False
);
COMMENT ON COLUMN "admin_users"."user_role" IS 'PROGRAM_COORDINATOR: PROGRAM_COORDINATOR\nSUPER_ADMIN: SUPER_ADMIN\nHEALTH_BUDDY: HEALTH_BUDDY';
CREATE TABLE IF NOT EXISTS "users_analyst_team" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "first_name" VARCHAR(50) NOT NULL DEFAULT '',
    "last_name" VARCHAR(50) NOT NULL DEFAULT '',
    "middle_name" VARCHAR(50) NOT NULL DEFAULT '',
    "username" VARCHAR(50) NOT NULL UNIQUE,
    "phone" VARCHAR(20) NOT NULL UNIQUE,
    "email" VARCHAR(100) DEFAULT '',
    "password" VARCHAR(255) NOT NULL DEFAULT '',
    "is_active" BOOL NOT NULL DEFAULT True,
    "is_verified" BOOL NOT NULL DEFAULT True,
    "profile_image" TEXT,
    "user_role" VARCHAR(15) NOT NULL DEFAULT 'PSYCHOLOGIST',
    "role_type" VARCHAR(50) NOT NULL DEFAULT 'ANALYST_TEAM',
    "dob" DATE,
    "gender" VARCHAR(20) NOT NULL DEFAULT '',
    "address_line_1" VARCHAR(100) NOT NULL DEFAULT '',
    "address_line_2" VARCHAR(100) NOT NULL DEFAULT '',
    "landmark" VARCHAR(100) NOT NULL DEFAULT '',
    "street_name" VARCHAR(100) NOT NULL DEFAULT '',
    "state" VARCHAR(50) NOT NULL DEFAULT '',
    "pincode" VARCHAR(10) NOT NULL DEFAULT '',
    "country_calling_code" VARCHAR(5) NOT NULL DEFAULT '',
    "country" VARCHAR(50) NOT NULL DEFAULT '',
    "location" VARCHAR(50) NOT NULL DEFAULT '',
    "blood_group" VARCHAR(10) DEFAULT '',
    "spoken_languages" TEXT,
    "days_available" TEXT,
    "employee_id" VARCHAR(50) UNIQUE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "created_user_role" VARCHAR(50) DEFAULT '',
    "created_role_type" VARCHAR(50) DEFAULT '',
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_user_role" VARCHAR(50) DEFAULT '',
    "updated_role_type" VARCHAR(50) DEFAULT '',
    "deleted_at" TIMESTAMPTZ,
    "is_deleted" BOOL NOT NULL DEFAULT False
);
COMMENT ON COLUMN "users_analyst_team"."user_role" IS 'NUTRITIONIST: NUTRITIONIST\nPSYCHOLOGIST: PSYCHOLOGIST\nMEDICAL_OFFICER: MEDICAL_OFFICER';
CREATE TABLE IF NOT EXISTS "users_consultant" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "first_name" VARCHAR(50) NOT NULL DEFAULT '',
    "last_name" VARCHAR(50) NOT NULL DEFAULT '',
    "middle_name" VARCHAR(50) NOT NULL DEFAULT '',
    "education" VARCHAR(50) NOT NULL DEFAULT '',
    "specialty" VARCHAR(50) NOT NULL DEFAULT '',
    "experience" VARCHAR(50) NOT NULL DEFAULT '',
    "location" VARCHAR(50) NOT NULL DEFAULT '',
    "state" VARCHAR(50) NOT NULL DEFAULT '',
    "country" VARCHAR(50) NOT NULL DEFAULT '',
    "pincode" VARCHAR(10) NOT NULL DEFAULT '',
    "user_role" VARCHAR(14) NOT NULL DEFAULT 'PEDIATRICIAN',
    "role_type" VARCHAR(50) NOT NULL DEFAULT 'CONSULTANT_TEAM',
    "phone" VARCHAR(20) NOT NULL UNIQUE DEFAULT '0000000000',
    "email" VARCHAR(100) NOT NULL DEFAULT '',
    "dob" DATE,
    "gender" VARCHAR(20) NOT NULL DEFAULT '',
    "address_line_1" VARCHAR(100) NOT NULL DEFAULT '',
    "address_line_2" VARCHAR(100) NOT NULL DEFAULT '',
    "landmark" VARCHAR(100) NOT NULL DEFAULT '',
    "street_name" VARCHAR(100) NOT NULL DEFAULT '',
    "country_calling_code" VARCHAR(5) NOT NULL DEFAULT '',
    "profile_image" VARCHAR(255) NOT NULL DEFAULT '',
    "username" VARCHAR(50) NOT NULL UNIQUE,
    "availability" VARCHAR(255) DEFAULT '',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "created_user_role" VARCHAR(50) DEFAULT '',
    "created_role_type" VARCHAR(50) DEFAULT '',
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_user_role" VARCHAR(50) DEFAULT '',
    "updated_role_type" VARCHAR(50) DEFAULT '',
    "deleted_at" TIMESTAMPTZ,
    "is_deleted" BOOL NOT NULL DEFAULT False
);
COMMENT ON COLUMN "users_consultant"."user_role" IS 'PEDIATRICIAN: PEDIATRICIAN\nDENTIST: DENTIST\nEYE_SPECIALIST: EYE_SPECIALIST\nNUTRITIONIST: NUTRITIONIST\nPSYCHOLOGIST: PSYCHOLOGIST';
CREATE TABLE IF NOT EXISTS "users_on_ground_team" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "first_name" VARCHAR(50) NOT NULL DEFAULT '',
    "last_name" VARCHAR(50) NOT NULL DEFAULT '',
    "middle_name" VARCHAR(50) NOT NULL DEFAULT '',
    "username" VARCHAR(50) NOT NULL UNIQUE,
    "phone" VARCHAR(20) NOT NULL UNIQUE,
    "email" VARCHAR(100) DEFAULT '',
    "password" VARCHAR(255) NOT NULL DEFAULT '',
    "is_active" BOOL NOT NULL DEFAULT True,
    "is_verified" BOOL NOT NULL DEFAULT True,
    "profile_image" VARCHAR(255) NOT NULL DEFAULT '',
    "role_type" VARCHAR(50) NOT NULL DEFAULT 'ON_GROUND_TEAM',
    "user_role" VARCHAR(17) NOT NULL DEFAULT 'REGISTRATION_TEAM',
    "dob" DATE,
    "gender" VARCHAR(20) NOT NULL DEFAULT '',
    "address_line_1" VARCHAR(100) NOT NULL DEFAULT '',
    "address_line_2" VARCHAR(100) NOT NULL DEFAULT '',
    "landmark" VARCHAR(100) NOT NULL DEFAULT '',
    "street_name" VARCHAR(100) NOT NULL DEFAULT '',
    "state" VARCHAR(50) NOT NULL DEFAULT '',
    "pincode" VARCHAR(10) NOT NULL DEFAULT '',
    "country_calling_code" VARCHAR(5) NOT NULL DEFAULT '',
    "country" VARCHAR(50) NOT NULL DEFAULT '',
    "location" VARCHAR(50) NOT NULL DEFAULT '',
    "blood_group" VARCHAR(10) DEFAULT '',
    "spoken_languages" TEXT,
    "days_available" TEXT,
    "employee_id" VARCHAR(50) UNIQUE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "created_user_role" VARCHAR(50) DEFAULT '',
    "created_role_type" VARCHAR(50) DEFAULT '',
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_user_role" VARCHAR(50) DEFAULT '',
    "updated_role_type" VARCHAR(50) DEFAULT '',
    "deleted_at" TIMESTAMPTZ,
    "is_deleted" BOOL NOT NULL DEFAULT False
);
COMMENT ON COLUMN "users_on_ground_team"."user_role" IS 'REGISTRATION_TEAM: REGISTRATION_TEAM\nCAMP_COORDINATOR: CAMP_COORDINATOR';
CREATE TABLE IF NOT EXISTS "users_parents" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "primary_first_name" VARCHAR(50) NOT NULL DEFAULT '',
    "primary_last_name" VARCHAR(50) NOT NULL DEFAULT '',
    "primary_middle_name" VARCHAR(50) NOT NULL DEFAULT '',
    "primary_mobile" VARCHAR(20) NOT NULL UNIQUE,
    "primary_email" VARCHAR(100) NOT NULL DEFAULT '',
    "primary_country_calling_code" VARCHAR(100) NOT NULL DEFAULT '',
    "country" VARCHAR(100) NOT NULL DEFAULT '',
    "secondary_first_name" VARCHAR(50) NOT NULL DEFAULT '',
    "secondary_last_name" VARCHAR(50) NOT NULL DEFAULT '',
    "secondary_middle_name" VARCHAR(50) NOT NULL DEFAULT '',
    "secondary_mobile" VARCHAR(20) NOT NULL DEFAULT '',
    "secondary_email" VARCHAR(100) NOT NULL DEFAULT '',
    "secondary_country_calling_code" VARCHAR(100) NOT NULL DEFAULT '',
    "is_active" BOOL NOT NULL DEFAULT True,
    "is_verified" BOOL NOT NULL DEFAULT True,
    "profile_image" VARCHAR(255) NOT NULL DEFAULT '',
    "location" VARCHAR(50) NOT NULL DEFAULT '',
    "user_role" VARCHAR(8) NOT NULL DEFAULT 'PARENT',
    "role_type" VARCHAR(50) NOT NULL DEFAULT 'PARENT',
    "dob" DATE,
    "gender" VARCHAR(20) NOT NULL DEFAULT '',
    "address_line_1" VARCHAR(100) NOT NULL DEFAULT '',
    "address_line_2" VARCHAR(100) NOT NULL DEFAULT '',
    "landmark" VARCHAR(100) NOT NULL DEFAULT '',
    "street_name" VARCHAR(100) NOT NULL DEFAULT '',
    "state" VARCHAR(100) NOT NULL DEFAULT '',
    "pincode" VARCHAR(100) NOT NULL DEFAULT '',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "created_user_role" VARCHAR(50) DEFAULT '',
    "created_role_type" VARCHAR(50) DEFAULT '',
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_user_role" VARCHAR(50) DEFAULT '',
    "updated_role_type" VARCHAR(50) DEFAULT '',
    "deleted_at" TIMESTAMPTZ,
    "is_deleted" BOOL NOT NULL DEFAULT False
);
COMMENT ON COLUMN "users_parents"."user_role" IS 'PARENT: PARENT\nGUARDIAN: GUARDIAN';
CREATE TABLE IF NOT EXISTS "users_screening_team" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "first_name" VARCHAR(50) NOT NULL DEFAULT '',
    "last_name" VARCHAR(50) NOT NULL DEFAULT '',
    "middle_name" VARCHAR(50) NOT NULL DEFAULT '',
    "username" VARCHAR(50) NOT NULL UNIQUE,
    "phone" VARCHAR(20) NOT NULL UNIQUE,
    "email" VARCHAR(100) NOT NULL DEFAULT '',
    "password" VARCHAR(255) NOT NULL DEFAULT '',
    "is_active" BOOL NOT NULL DEFAULT True,
    "is_verified" BOOL NOT NULL DEFAULT True,
    "profile_image" VARCHAR(255) NOT NULL DEFAULT '',
    "user_role" VARCHAR(18) NOT NULL DEFAULT 'PHYSICAL_WELLBEING',
    "role_type" VARCHAR(50) NOT NULL DEFAULT 'SCREENING_TEAM',
    "dob" DATE,
    "gender" VARCHAR(20) NOT NULL DEFAULT '',
    "address_line_1" VARCHAR(100) NOT NULL DEFAULT '',
    "address_line_2" VARCHAR(100) NOT NULL DEFAULT '',
    "landmark" VARCHAR(100) NOT NULL DEFAULT '',
    "street_name" VARCHAR(100) NOT NULL DEFAULT '',
    "state" VARCHAR(50) NOT NULL DEFAULT '',
    "pincode" VARCHAR(10) NOT NULL DEFAULT '',
    "country_calling_code" VARCHAR(5) NOT NULL DEFAULT '',
    "country" VARCHAR(50) NOT NULL DEFAULT '',
    "location" VARCHAR(50) NOT NULL DEFAULT '',
    "blood_group" VARCHAR(10) DEFAULT '',
    "spoken_languages" TEXT,
    "days_available" TEXT,
    "employee_id" VARCHAR(50) UNIQUE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "created_user_role" VARCHAR(50) DEFAULT '',
    "created_role_type" VARCHAR(50) DEFAULT '',
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_user_role" VARCHAR(50) DEFAULT '',
    "updated_role_type" VARCHAR(50) DEFAULT '',
    "deleted_at" TIMESTAMPTZ,
    "is_deleted" BOOL NOT NULL DEFAULT False
);
COMMENT ON COLUMN "users_screening_team"."user_role" IS 'PHYSICAL_WELLBEING: PHYSICAL_WELLBEING\nDENTIST: DENTIST\nEYE_SPECIALIST: EYE_SPECIALIST\nNUTRITIONIST: NUTRITIONIST\nPSYCHOLOGIST: PSYCHOLOGIST';
CREATE TABLE IF NOT EXISTS "lab_tests" (
    "test_id" BIGSERIAL NOT NULL PRIMARY KEY,
    "test_name" VARCHAR(400) NOT NULL UNIQUE,
    "description" TEXT,
    "price" DECIMAL(10,2) NOT NULL,
    "status" INT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "created_user_role" VARCHAR(50) DEFAULT '',
    "created_role_type" VARCHAR(50) DEFAULT '',
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_user_role" VARCHAR(50) DEFAULT '',
    "updated_role_type" VARCHAR(50) DEFAULT '',
    "deleted_at" TIMESTAMPTZ,
    "is_deleted" BOOL NOT NULL DEFAULT False
);
CREATE TABLE IF NOT EXISTS "questionnaire" (
    "question_id" BIGSERIAL NOT NULL PRIMARY KEY,
    "question" VARCHAR(255) NOT NULL,
    "type" VARCHAR(100) NOT NULL DEFAULT '',
    "sub_type" VARCHAR(100) NOT NULL DEFAULT '',
    "group" VARCHAR(100) NOT NULL DEFAULT '',
    "status" BOOL NOT NULL DEFAULT True,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "created_user_role" VARCHAR(50) DEFAULT '',
    "created_role_type" VARCHAR(50) DEFAULT '',
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_user_role" VARCHAR(50) DEFAULT '',
    "updated_role_type" VARCHAR(50) DEFAULT ''
);
CREATE TABLE IF NOT EXISTS "vaccinations" (
    "vaccine_id" BIGSERIAL NOT NULL PRIMARY KEY,
    "vaccine_name" VARCHAR(255) NOT NULL DEFAULT '',
    "age" VARCHAR(255) NOT NULL DEFAULT '',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "created_user_role" VARCHAR(50) DEFAULT '',
    "created_role_type" VARCHAR(50) DEFAULT '',
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_user_role" VARCHAR(50) DEFAULT '',
    "updated_role_type" VARCHAR(50) DEFAULT '',
    "deleted_at" TIMESTAMPTZ,
    "is_deleted" BOOL NOT NULL DEFAULT False
);
CREATE TABLE IF NOT EXISTS "hp_assign_school" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "date" DATE,
    "from_time" VARCHAR(20) NOT NULL DEFAULT '',
    "to_time" VARCHAR(20) NOT NULL DEFAULT '',
    "team_type" VARCHAR(50) NOT NULL DEFAULT '',
    "team_role" VARCHAR(50) NOT NULL DEFAULT '',
    "user_id" BIGINT NOT NULL,
    "school" BIGINT NOT NULL,
    "class_no" VARCHAR(10) NOT NULL DEFAULT '',
    "section" VARCHAR(10) NOT NULL DEFAULT '',
    "is_completed" BOOL NOT NULL DEFAULT False,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "created_user_role" VARCHAR(50) DEFAULT '',
    "created_role_type" VARCHAR(50) DEFAULT '',
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_user_role" VARCHAR(50) DEFAULT '',
    "updated_role_type" VARCHAR(50) DEFAULT '',
    "deleted_at" TIMESTAMPTZ,
    "is_deleted" BOOL NOT NULL DEFAULT False
);
CREATE TABLE IF NOT EXISTS "health_passport_schools" (
    "school_id" BIGSERIAL NOT NULL PRIMARY KEY,
    "school_name" VARCHAR(100) NOT NULL DEFAULT '',
    "school_full_name" VARCHAR(255) NOT NULL DEFAULT '',
    "school_logo" VARCHAR(255) NOT NULL DEFAULT '',
    "school_location_link" VARCHAR(500) DEFAULT '',
    "school_code" VARCHAR(20) NOT NULL UNIQUE,
    "registration_no" VARCHAR(255) NOT NULL DEFAULT '',
    "country_code" VARCHAR(20) NOT NULL DEFAULT '',
    "phone" VARCHAR(20) NOT NULL DEFAULT '',
    "primary_contact_fullname" VARCHAR(50) NOT NULL DEFAULT '',
    "primary_contact_email" VARCHAR(50) NOT NULL DEFAULT '',
    "primary_contact_phone" VARCHAR(50) NOT NULL DEFAULT '',
    "location" TEXT NOT NULL,
    "admin_contact_fullname" VARCHAR(50) NOT NULL DEFAULT '',
    "admin_contact_email" VARCHAR(50) NOT NULL DEFAULT '',
    "admin_contact_phone" VARCHAR(20) NOT NULL DEFAULT '',
    "address_line1" VARCHAR(255) NOT NULL DEFAULT '',
    "address_line2" VARCHAR(255) NOT NULL DEFAULT '',
    "landmark" VARCHAR(100) NOT NULL DEFAULT '',
    "street" VARCHAR(100) NOT NULL DEFAULT '',
    "state" VARCHAR(50) NOT NULL DEFAULT '',
    "pincode" VARCHAR(10) NOT NULL DEFAULT '',
    "country" VARCHAR(50) NOT NULL DEFAULT '',
    "status" BOOL NOT NULL DEFAULT True,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "created_user_role" VARCHAR(50) DEFAULT '',
    "created_role_type" VARCHAR(50) DEFAULT '',
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_user_role" VARCHAR(50) DEFAULT '',
    "updated_role_type" VARCHAR(50) DEFAULT '',
    "deleted_at" TIMESTAMPTZ,
    "is_deleted" BOOL NOT NULL DEFAULT False
);
CREATE TABLE IF NOT EXISTS "users_school_staff" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "first_name" VARCHAR(50) NOT NULL DEFAULT '',
    "last_name" VARCHAR(50) NOT NULL DEFAULT '',
    "middle_name" VARCHAR(50) NOT NULL DEFAULT '',
    "username" VARCHAR(50) NOT NULL UNIQUE,
    "password" VARCHAR(255) NOT NULL DEFAULT '',
    "phone" VARCHAR(20) NOT NULL UNIQUE,
    "email" VARCHAR(100) NOT NULL DEFAULT '',
    "is_active" BOOL NOT NULL DEFAULT True,
    "is_verified" BOOL NOT NULL DEFAULT True,
    "profile_image" VARCHAR(255) NOT NULL DEFAULT '',
    "class_room" VARCHAR(10) NOT NULL DEFAULT '',
    "section" VARCHAR(2) NOT NULL DEFAULT '',
    "user_role" VARCHAR(12) NOT NULL DEFAULT 'TEACHER',
    "role_type" VARCHAR(50) NOT NULL DEFAULT 'SCHOOL_STAFF',
    "street" VARCHAR(100) NOT NULL DEFAULT '',
    "state" VARCHAR(100) NOT NULL DEFAULT '',
    "pincode" VARCHAR(10) NOT NULL DEFAULT '',
    "country" VARCHAR(50) NOT NULL DEFAULT '',
    "dob" DATE,
    "gender" VARCHAR(20) NOT NULL DEFAULT '',
    "address_line_1" VARCHAR(100) NOT NULL DEFAULT '',
    "address_line_2" VARCHAR(100) NOT NULL DEFAULT '',
    "landmark" VARCHAR(100) NOT NULL DEFAULT '',
    "country_calling_code" VARCHAR(5) NOT NULL DEFAULT '',
    "location" VARCHAR(50) NOT NULL DEFAULT '',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "created_user_role" VARCHAR(50) DEFAULT '',
    "created_role_type" VARCHAR(50) DEFAULT '',
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_user_role" VARCHAR(50) DEFAULT '',
    "updated_role_type" VARCHAR(50) DEFAULT '',
    "deleted_at" TIMESTAMPTZ,
    "is_deleted" BOOL NOT NULL DEFAULT False,
    "school_id" BIGINT REFERENCES "health_passport_schools" ("school_id") ON DELETE SET NULL
);
COMMENT ON COLUMN "users_school_staff"."user_role" IS 'SCHOOL_ADMIN: SCHOOL_ADMIN\nTEACHER: TEACHER';
CREATE TABLE IF NOT EXISTS "behavioural_checklist" (
    "bc_id" SERIAL NOT NULL PRIMARY KEY,
    "type" VARCHAR(100) NOT NULL DEFAULT '',
    "name" TEXT NOT NULL,
    "status" BOOL NOT NULL DEFAULT True,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "created_user_role" VARCHAR(50) DEFAULT '',
    "created_role_type" VARCHAR(50) DEFAULT '',
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_user_role" VARCHAR(50) DEFAULT '',
    "updated_role_type" VARCHAR(50) DEFAULT '',
    "deleted_at" TIMESTAMPTZ,
    "is_deleted" BOOL NOT NULL DEFAULT False
);
CREATE TABLE IF NOT EXISTS "nutrition_checklist" (
    "nutrition_id" SERIAL NOT NULL PRIMARY KEY,
    "name" VARCHAR(20) NOT NULL UNIQUE,
    "status" BOOL NOT NULL DEFAULT False,
    "nutrition_type" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "created_user_role" VARCHAR(50) DEFAULT '',
    "created_role_type" VARCHAR(50) DEFAULT '',
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_user_role" VARCHAR(50) DEFAULT '',
    "updated_role_type" VARCHAR(50) DEFAULT '',
    "deleted_at" TIMESTAMPTZ,
    "is_deleted" BOOL NOT NULL DEFAULT False
);
CREATE TABLE IF NOT EXISTS "screening_reports" (
    "sr_id" BIGSERIAL NOT NULL PRIMARY KEY,
    "report_type" VARCHAR(50) NOT NULL DEFAULT '',
    "report_sub_type" TEXT NOT NULL,
    "key" VARCHAR(50) NOT NULL DEFAULT '',
    "value" TEXT NOT NULL,
    "status" BOOL NOT NULL DEFAULT True,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "created_user_role" VARCHAR(50) DEFAULT '',
    "created_role_type" VARCHAR(50) DEFAULT '',
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_user_role" VARCHAR(50) DEFAULT '',
    "updated_role_type" VARCHAR(50) DEFAULT '',
    "deleted_at" TIMESTAMPTZ,
    "is_deleted" BOOL NOT NULL DEFAULT False
);
CREATE TABLE IF NOT EXISTS "transactions" (
    "tx_id" BIGSERIAL NOT NULL PRIMARY KEY,
    "tx_no" VARCHAR(30) NOT NULL UNIQUE,
    "invoice_no" VARCHAR(50) NOT NULL UNIQUE,
    "tx_mode" VARCHAR(50) NOT NULL DEFAULT '',
    "tx_type" VARCHAR(50) NOT NULL DEFAULT '',
    "tx_amnt" DECIMAL(10,2) NOT NULL DEFAULT 0,
    "tx_datetime" TIMESTAMPTZ NOT NULL,
    "tx_status" BOOL NOT NULL DEFAULT False,
    "discount_amnt" DECIMAL(10,2) NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "created_user_role" VARCHAR(50) DEFAULT '',
    "created_role_type" VARCHAR(50) DEFAULT '',
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_user_role" VARCHAR(50) DEFAULT '',
    "updated_role_type" VARCHAR(50) DEFAULT '',
    "deleted_at" TIMESTAMPTZ,
    "is_deleted" BOOL NOT NULL DEFAULT False
);
CREATE TABLE IF NOT EXISTS "consultations" (
    "consult_id" BIGSERIAL NOT NULL PRIMARY KEY,
    "slot_date" DATE NOT NULL,
    "slot_time" TIMETZ NOT NULL,
    "consult_fee" DECIMAL(10,2) NOT NULL,
    "booking_status" VARCHAR(100) NOT NULL DEFAULT 'pending',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "created_user_role" VARCHAR(50) DEFAULT '',
    "created_role_type" VARCHAR(50) DEFAULT '',
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_user_role" VARCHAR(50) DEFAULT '',
    "updated_role_type" VARCHAR(50) DEFAULT '',
    "deleted_at" TIMESTAMPTZ,
    "is_deleted" BOOL NOT NULL DEFAULT False,
    "doctor_id" BIGINT NOT NULL REFERENCES "users_consultant" ("id") ON DELETE CASCADE,
    "patient_id" BIGINT NOT NULL REFERENCES "students" ("id") ON DELETE CASCADE,
    "tx_id" BIGINT NOT NULL REFERENCES "transactions" ("tx_id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "idx_consultatio_doctor__4b1af8" ON "consultations" ("doctor_id");
CREATE INDEX IF NOT EXISTS "idx_consultatio_patient_7b3ec9" ON "consultations" ("patient_id");
CREATE INDEX IF NOT EXISTS "idx_consultatio_tx_id_d396af" ON "consultations" ("tx_id");
CREATE TABLE IF NOT EXISTS "transaction_details" (
    "tx_detail_id" BIGSERIAL NOT NULL PRIMARY KEY,
    "item" VARCHAR(100) NOT NULL DEFAULT '',
    "price" DECIMAL(10,2) NOT NULL DEFAULT 0,
    "discount_amnt" DECIMAL(10,2) NOT NULL DEFAULT 0,
    "quantity" INT NOT NULL DEFAULT 0,
    "tax" DECIMAL(10,2) NOT NULL DEFAULT 0,
    "sub_total" DECIMAL(10,2) NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "created_user_role" VARCHAR(50) DEFAULT '',
    "created_role_type" VARCHAR(50) DEFAULT '',
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_user_role" VARCHAR(50) DEFAULT '',
    "updated_role_type" VARCHAR(50) DEFAULT '',
    "deleted_at" TIMESTAMPTZ,
    "is_deleted" BOOL NOT NULL DEFAULT False,
    "tx_id" BIGINT NOT NULL REFERENCES "transactions" ("tx_id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "idx_transaction_tx_id_cfa30f" ON "transaction_details" ("tx_id");
CREATE TABLE IF NOT EXISTS "students" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "first_name" VARCHAR(50) NOT NULL DEFAULT '',
    "middle_name" VARCHAR(50) NOT NULL DEFAULT '',
    "last_name" VARCHAR(50) NOT NULL DEFAULT '',
    "gender" VARCHAR(10) NOT NULL DEFAULT '',
    "dob" DATE NOT NULL,
    "class_room" VARCHAR(50) NOT NULL DEFAULT '',
    "section" VARCHAR(10) NOT NULL DEFAULT '',
    "roll_no" VARCHAR(50) NOT NULL DEFAULT '',
    "aadhaar_no" VARCHAR(20) NOT NULL DEFAULT '',
    "abha_id" VARCHAR(50) NOT NULL DEFAULT '',
    "mp_uhid" VARCHAR(50) NOT NULL DEFAULT '',
    "food_preferences" VARCHAR(255) NOT NULL DEFAULT '',
    "address_line1" VARCHAR(255) NOT NULL DEFAULT '',
    "address_line2" VARCHAR(255) NOT NULL DEFAULT '',
    "landmark" VARCHAR(255) NOT NULL DEFAULT '',
    "street" VARCHAR(255) NOT NULL DEFAULT '',
    "state" VARCHAR(50) NOT NULL DEFAULT '',
    "pincode" VARCHAR(50) NOT NULL DEFAULT '',
    "country_code" VARCHAR(50) NOT NULL DEFAULT '',
    "phone" VARCHAR(255) NOT NULL DEFAULT '',
    "country" VARCHAR(255) NOT NULL DEFAULT '',
    "blood_group" VARCHAR(10) NOT NULL DEFAULT '',
    "profile_image" VARCHAR(255) NOT NULL DEFAULT '',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "created_user_role" VARCHAR(50) DEFAULT '',
    "created_role_type" VARCHAR(50) DEFAULT '',
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_user_role" VARCHAR(50) DEFAULT '',
    "updated_role_type" VARCHAR(50) DEFAULT '',
    "deleted_at" TIMESTAMPTZ,
    "is_deleted" BOOL NOT NULL DEFAULT False
);
CREATE TABLE IF NOT EXISTS "clinical_findings" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "user_id" BIGINT NOT NULL,
    "role_type" VARCHAR(50) NOT NULL,
    "role_name" VARCHAR(100) NOT NULL,
    "findings_data" JSONB NOT NULL,
    "strengths" TEXT NOT NULL,
    "need_attention" TEXT NOT NULL,
    "clinical_notes_recommendations" TEXT NOT NULL,
    "summary" TEXT NOT NULL,
    "status" VARCHAR(50),
    "analysis_status" BOOL NOT NULL DEFAULT False,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "created_user_role" VARCHAR(50) DEFAULT '',
    "created_role_type" VARCHAR(50) DEFAULT '',
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_user_role" VARCHAR(50) DEFAULT '',
    "updated_role_type" VARCHAR(50) DEFAULT '',
    "deleted_at" TIMESTAMPTZ,
    "is_deleted" BOOL NOT NULL DEFAULT False,
    "student_id" BIGINT NOT NULL REFERENCES "students" ("id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "idx_clinical_fi_student_caa0e5" ON "clinical_findings" ("student_id");
CREATE TABLE IF NOT EXISTS "clinical_recomendations" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "user_id" BIGINT NOT NULL,
    "report_type" VARCHAR(100) NOT NULL,
    "questions_data" JSONB,
    "summary" TEXT,
    "status" VARCHAR(50),
    "common_summary" TEXT,
    "common_status" VARCHAR(50),
    "clinical_notes" TEXT,
    "role_type" VARCHAR(50) NOT NULL,
    "role_name" VARCHAR(100) NOT NULL,
    "analysis_status" BOOL NOT NULL DEFAULT False,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "created_user_role" VARCHAR(50) DEFAULT '',
    "created_role_type" VARCHAR(50) DEFAULT '',
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_user_role" VARCHAR(50) DEFAULT '',
    "updated_role_type" VARCHAR(50) DEFAULT '',
    "deleted_at" TIMESTAMPTZ,
    "is_deleted" BOOL NOT NULL DEFAULT False,
    "student_id" BIGINT NOT NULL REFERENCES "students" ("id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "idx_clinical_re_student_73ac3c" ON "clinical_recomendations" ("student_id");
CREATE TABLE IF NOT EXISTS "contact_transcriptions" (
    "transcript_id" BIGSERIAL NOT NULL PRIMARY KEY,
    "contact_number" VARCHAR(20) NOT NULL DEFAULT '',
    "audio_file" TEXT NOT NULL,
    "transcription_text" TEXT NOT NULL,
    "status" BOOL NOT NULL DEFAULT True,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "created_user_role" VARCHAR(50) DEFAULT '',
    "created_role_type" VARCHAR(50) DEFAULT '',
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_user_role" VARCHAR(50) DEFAULT '',
    "updated_role_type" VARCHAR(50) DEFAULT '',
    "deleted_at" TIMESTAMPTZ,
    "is_deleted" BOOL NOT NULL DEFAULT False,
    "parent_id" BIGINT NOT NULL REFERENCES "users_parents" ("id") ON DELETE CASCADE,
    "student_id" BIGINT NOT NULL REFERENCES "students" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "student_lab_test_reports" (
    "slt_id" BIGSERIAL NOT NULL PRIMARY KEY,
    "price" DECIMAL(10,2) DEFAULT 0,
    "note" TEXT NOT NULL,
    "status" BOOL NOT NULL DEFAULT True,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "created_user_role" VARCHAR(50) DEFAULT '',
    "created_role_type" VARCHAR(50) DEFAULT '',
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_user_role" VARCHAR(50) DEFAULT '',
    "updated_role_type" VARCHAR(50) DEFAULT '',
    "deleted_at" TIMESTAMPTZ,
    "is_deleted" BOOL NOT NULL DEFAULT False,
    "student_id" BIGINT NOT NULL REFERENCES "students" ("id") ON DELETE CASCADE,
    "test_id" BIGINT NOT NULL REFERENCES "lab_tests" ("test_id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "student_questionnaire" (
    "sq_id" BIGSERIAL NOT NULL PRIMARY KEY,
    "answer" VARCHAR(255) NOT NULL DEFAULT '',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "created_user_role" VARCHAR(50) DEFAULT '',
    "created_role_type" VARCHAR(50) DEFAULT '',
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_user_role" VARCHAR(50) DEFAULT '',
    "updated_role_type" VARCHAR(50) DEFAULT '',
    "deleted_at" TIMESTAMPTZ,
    "is_deleted" BOOL NOT NULL DEFAULT False,
    "question_id" BIGINT NOT NULL REFERENCES "questionnaire" ("question_id") ON DELETE CASCADE,
    "student_id" BIGINT NOT NULL REFERENCES "students" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "student_vaccination" (
    "sv_id" BIGSERIAL NOT NULL PRIMARY KEY,
    "status" BOOL NOT NULL DEFAULT True,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "created_user_role" VARCHAR(50) DEFAULT '',
    "created_role_type" VARCHAR(50) DEFAULT '',
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_user_role" VARCHAR(50) DEFAULT '',
    "updated_role_type" VARCHAR(50) DEFAULT '',
    "deleted_at" TIMESTAMPTZ,
    "is_deleted" BOOL NOT NULL DEFAULT False,
    "student_id" BIGINT NOT NULL REFERENCES "students" ("id") ON DELETE CASCADE,
    "vaccine_id" BIGINT NOT NULL REFERENCES "vaccinations" ("vaccine_id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "idx_student_vac_student_73c5de" ON "student_vaccination" ("student_id");
CREATE INDEX IF NOT EXISTS "idx_student_vac_vaccine_0c63ed" ON "student_vaccination" ("vaccine_id");
CREATE TABLE IF NOT EXISTS "behavioural_screening" (
    "bs_id" BIGSERIAL NOT NULL PRIMARY KEY,
    "socialisation" JSONB NOT NULL,
    "communication" JSONB NOT NULL,
    "play_behaviour" JSONB NOT NULL,
    "interaction" JSONB NOT NULL,
    "anxiety_withdrawal" JSONB NOT NULL,
    "problem_behaviour" JSONB NOT NULL,
    "summary_concerns" JSONB NOT NULL,
    "recommendations" JSONB NOT NULL,
    "gross_motor_skills" TEXT NOT NULL,
    "note" TEXT NOT NULL,
    "next_followup" TEXT NOT NULL,
    "screening_status" BOOL NOT NULL DEFAULT False,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "created_user_role" VARCHAR(50) DEFAULT '',
    "created_role_type" VARCHAR(50) DEFAULT '',
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_user_role" VARCHAR(50) DEFAULT '',
    "updated_role_type" VARCHAR(50) DEFAULT '',
    "deleted_at" TIMESTAMPTZ,
    "is_deleted" BOOL NOT NULL DEFAULT False,
    "doctor_id" BIGINT REFERENCES "users_consultant" ("id") ON DELETE CASCADE,
    "student_id" BIGINT NOT NULL REFERENCES "students" ("id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "idx_behavioural_student_7193d4" ON "behavioural_screening" ("student_id");
CREATE TABLE IF NOT EXISTS "dental_screening" (
    "ds_id" BIGSERIAL NOT NULL PRIMARY KEY,
    "patient_concern" TEXT NOT NULL,
    "oral_examination" TEXT NOT NULL,
    "examination_note" TEXT NOT NULL,
    "diagnosis" TEXT NOT NULL,
    "treatment_recommendations" TEXT NOT NULL,
    "report_summary" TEXT NOT NULL,
    "screening_status" BOOL NOT NULL DEFAULT False,
    "status" VARCHAR(50),
    "next_followup" TEXT NOT NULL,
    "treatment_recommendations_note" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "created_user_role" VARCHAR(50) DEFAULT '',
    "created_role_type" VARCHAR(50) DEFAULT '',
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_user_role" VARCHAR(50) DEFAULT '',
    "updated_role_type" VARCHAR(50) DEFAULT '',
    "deleted_at" TIMESTAMPTZ,
    "is_deleted" BOOL NOT NULL DEFAULT False,
    "screening_user_id" BIGINT NOT NULL REFERENCES "users_screening_team" ("id") ON DELETE CASCADE,
    "student_id" BIGINT NOT NULL REFERENCES "students" ("id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "idx_dental_scre_screeni_6ac8dd" ON "dental_screening" ("screening_user_id");
CREATE INDEX IF NOT EXISTS "idx_dental_scre_student_c17552" ON "dental_screening" ("student_id");
CREATE TABLE IF NOT EXISTS "eye_screening" (
    "es_id" BIGSERIAL NOT NULL PRIMARY KEY,
    "patient_concern" TEXT NOT NULL,
    "vision_lefteye_res" TEXT NOT NULL,
    "vision_righteye_res" TEXT NOT NULL,
    "additional_find" TEXT NOT NULL,
    "report_summary" TEXT NOT NULL,
    "recommendations" TEXT NOT NULL,
    "next_followup" TEXT NOT NULL,
    "screening_status" BOOL NOT NULL DEFAULT False,
    "status" VARCHAR(50),
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "created_user_role" VARCHAR(50) DEFAULT '',
    "created_role_type" VARCHAR(50) DEFAULT '',
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_user_role" VARCHAR(50) DEFAULT '',
    "updated_role_type" VARCHAR(50) DEFAULT '',
    "deleted_at" TIMESTAMPTZ,
    "is_deleted" BOOL NOT NULL DEFAULT False,
    "screening_user_id" BIGINT NOT NULL REFERENCES "users_screening_team" ("id") ON DELETE CASCADE,
    "student_id" BIGINT NOT NULL REFERENCES "students" ("id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "idx_eye_screeni_screeni_6bf496" ON "eye_screening" ("screening_user_id");
CREATE INDEX IF NOT EXISTS "idx_eye_screeni_student_f07f9f" ON "eye_screening" ("student_id");
CREATE TABLE IF NOT EXISTS "nutrition_screening" (
    "ns_id" BIGSERIAL NOT NULL PRIMARY KEY,
    "eyes" TEXT NOT NULL,
    "hair" TEXT NOT NULL,
    "mouth_lips" TEXT NOT NULL,
    "skin" TEXT NOT NULL,
    "nails" TEXT NOT NULL,
    "teeth" TEXT NOT NULL,
    "general_signs" TEXT NOT NULL,
    "bone_muscle" TEXT NOT NULL,
    "note" TEXT NOT NULL,
    "screening_status" BOOL NOT NULL DEFAULT False,
    "next_followup" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "created_user_role" VARCHAR(50) DEFAULT '',
    "created_role_type" VARCHAR(50) DEFAULT '',
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_user_role" VARCHAR(50) DEFAULT '',
    "updated_role_type" VARCHAR(50) DEFAULT '',
    "deleted_at" TIMESTAMPTZ,
    "is_deleted" BOOL NOT NULL DEFAULT False,
    "doctor_id" BIGINT REFERENCES "users_consultant" ("id") ON DELETE CASCADE,
    "student_id" BIGINT NOT NULL REFERENCES "students" ("id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "idx_nutrition_s_student_19591d" ON "nutrition_screening" ("student_id");
CREATE TABLE IF NOT EXISTS "screening_questions_answers" (
    "sqa_id" BIGSERIAL NOT NULL PRIMARY KEY,
    "question" TEXT NOT NULL,
    "answer" TEXT NOT NULL,
    "screening_type" VARCHAR(100) NOT NULL DEFAULT '',
    "doctor" INT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "created_user_role" VARCHAR(50) DEFAULT '',
    "created_role_type" VARCHAR(50) DEFAULT '',
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_user_role" VARCHAR(50) DEFAULT '',
    "updated_role_type" VARCHAR(50) DEFAULT '',
    "deleted_at" TIMESTAMPTZ,
    "is_deleted" BOOL NOT NULL DEFAULT False,
    "student_id" BIGINT NOT NULL REFERENCES "students" ("id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "idx_screening_q_student_ea02a6" ON "screening_questions_answers" ("student_id");
CREATE TABLE IF NOT EXISTS "screening_analysis_checklist" (
    "ssa_id" BIGSERIAL NOT NULL PRIMARY KEY,
    "physical_screening" BOOL NOT NULL DEFAULT False,
    "nutrition_screening" BOOL NOT NULL DEFAULT False,
    "emotional_screening" BOOL NOT NULL DEFAULT False,
    "dental_screening" BOOL NOT NULL DEFAULT False,
    "ophthalmologist_screening" BOOL NOT NULL DEFAULT False,
    "lab_test" BOOL NOT NULL DEFAULT False,
    "health_afficer" BOOL NOT NULL DEFAULT False,
    "physical_analysis" BOOL NOT NULL DEFAULT False,
    "nutrition_analysis" BOOL NOT NULL DEFAULT False,
    "emotional_analysis" BOOL NOT NULL DEFAULT False,
    "dental_analysis" BOOL NOT NULL DEFAULT False,
    "ophtalmologist_analysis" BOOL NOT NULL DEFAULT False,
    "medical_officer" BOOL NOT NULL DEFAULT False,
    "final_report_generation" BOOL NOT NULL DEFAULT False,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "created_user_role" VARCHAR(50) DEFAULT '',
    "created_role_type" VARCHAR(50) DEFAULT '',
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_user_role" VARCHAR(50) DEFAULT '',
    "updated_role_type" VARCHAR(50) DEFAULT '',
    "deleted_at" TIMESTAMPTZ,
    "is_deleted" BOOL NOT NULL DEFAULT False,
    "student_id" BIGINT NOT NULL REFERENCES "students" ("id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "idx_screening_a_student_36d30f" ON "screening_analysis_checklist" ("student_id");
CREATE TABLE IF NOT EXISTS "screening_reports_summary" (
    "srs_id" BIGSERIAL NOT NULL PRIMARY KEY,
    "screening_type" VARCHAR(50) NOT NULL DEFAULT '',
    "status" VARCHAR(50) NOT NULL DEFAULT '',
    "description" TEXT NOT NULL,
    "good_outcomes_type" TEXT NOT NULL,
    "good_outcomes_remarks" TEXT NOT NULL,
    "areas_of_concern_type" TEXT NOT NULL,
    "areas_of_concern_remarks" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "created_user_role" VARCHAR(50) DEFAULT '',
    "created_role_type" VARCHAR(50) DEFAULT '',
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_user_role" VARCHAR(50) DEFAULT '',
    "updated_role_type" VARCHAR(50) DEFAULT '',
    "deleted_at" TIMESTAMPTZ,
    "is_deleted" BOOL NOT NULL DEFAULT False,
    "student_id" BIGINT NOT NULL REFERENCES "students" ("id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "idx_screening_r_student_c5b6c1" ON "screening_reports_summary" ("student_id");
CREATE TABLE IF NOT EXISTS "attendance_status" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "attendance_status" BOOL NOT NULL DEFAULT False,
    "date" DATE NOT NULL,
    "user_id" BIGINT NOT NULL,
    "role" VARCHAR(50) NOT NULL,
    "role_type" VARCHAR(50) NOT NULL,
    "school_id" BIGINT NOT NULL,
    "class_name" VARCHAR(50) NOT NULL,
    "section" VARCHAR(10) NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "created_user_role" VARCHAR(50) DEFAULT '',
    "created_role_type" VARCHAR(50) DEFAULT '',
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_user_role" VARCHAR(50) DEFAULT '',
    "updated_role_type" VARCHAR(50) DEFAULT '',
    "deleted_at" TIMESTAMPTZ,
    "is_deleted" BOOL NOT NULL DEFAULT False,
    "student_id" BIGINT NOT NULL REFERENCES "students" ("id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "idx_attendance__student_a80f37" ON "attendance_status" ("student_id");
CREATE TABLE IF NOT EXISTS "parent_children" (
    "pc_id" BIGSERIAL NOT NULL PRIMARY KEY,
    "primary_phone_no" VARCHAR(20) NOT NULL,
    "secondary_phone_no" VARCHAR(20) NOT NULL,
    "status" BOOL NOT NULL DEFAULT True,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "created_user_role" VARCHAR(50) DEFAULT '',
    "created_role_type" VARCHAR(50) DEFAULT '',
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_user_role" VARCHAR(50) DEFAULT '',
    "updated_role_type" VARCHAR(50) DEFAULT '',
    "deleted_at" TIMESTAMPTZ,
    "is_deleted" BOOL NOT NULL DEFAULT False,
    "parent_id" BIGINT NOT NULL REFERENCES "users_parents" ("id") ON DELETE CASCADE,
    "student_id" BIGINT NOT NULL REFERENCES "students" ("id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "idx_parent_chil_parent__efe447" ON "parent_children" ("parent_id");
CREATE INDEX IF NOT EXISTS "idx_parent_chil_student_add387" ON "parent_children" ("student_id");
CREATE TABLE IF NOT EXISTS "school_students" (
    "ss_id" BIGSERIAL NOT NULL PRIMARY KEY,
    "status" BOOL NOT NULL DEFAULT True,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "created_user_role" VARCHAR(50) DEFAULT '',
    "created_role_type" VARCHAR(50) DEFAULT '',
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_user_role" VARCHAR(50) DEFAULT '',
    "updated_role_type" VARCHAR(50) DEFAULT '',
    "deleted_at" TIMESTAMPTZ,
    "is_deleted" BOOL NOT NULL DEFAULT False,
    "school_id" BIGINT NOT NULL REFERENCES "health_passport_schools" ("school_id") ON DELETE CASCADE,
    "student_id" BIGINT NOT NULL REFERENCES "students" ("id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "idx_school_stud_school__5aa8c1" ON "school_students" ("school_id");
CREATE INDEX IF NOT EXISTS "idx_school_stud_student_4f248e" ON "school_students" ("student_id");
CREATE TABLE IF NOT EXISTS "student_smart_scale" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "height_cm" DOUBLE PRECISION DEFAULT 0,
    "age_years" INT DEFAULT 0,
    "weighing_time" TIMESTAMPTZ,
    "body_weight_kg" DOUBLE PRECISION DEFAULT 0,
    "body_fat_rate_percent" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "device_mac" VARCHAR(50) DEFAULT '',
    "inorganic_salt_content_kg" DOUBLE PRECISION DEFAULT 0,
    "obesity_percent" DOUBLE PRECISION DEFAULT 0,
    "water_content_kg" DOUBLE PRECISION DEFAULT 0,
    "protein_content_kg" DOUBLE PRECISION DEFAULT 0,
    "subcutaneous_fat_volume_kg" DOUBLE PRECISION DEFAULT 0,
    "bmi" DOUBLE PRECISION DEFAULT 0,
    "fat_content_kg" DOUBLE PRECISION DEFAULT 0,
    "muscle_rate_percent" DOUBLE PRECISION DEFAULT 0,
    "muscle_mass_kg" DOUBLE PRECISION DEFAULT 0,
    "visceral_fat_level" DOUBLE PRECISION DEFAULT 0,
    "bmr" DOUBLE PRECISION DEFAULT 0,
    "body_moisture_content_percent" DOUBLE PRECISION DEFAULT 0,
    "bone_mass_kg" DOUBLE PRECISION DEFAULT 0,
    "internal_protein_rate_percent" DOUBLE PRECISION DEFAULT 0,
    "skeletal_muscle_rate_percent" DOUBLE PRECISION DEFAULT 0,
    "lean_body_mass_kg" DOUBLE PRECISION DEFAULT 0,
    "heart_rate_beats_min" INT DEFAULT 0,
    "physical_score" INT DEFAULT 0,
    "body_type" INT DEFAULT 0,
    "physical_age" INT DEFAULT 0,
    "subcutaneous_fat_rate" DOUBLE PRECISION DEFAULT 0,
    "health_level" INT DEFAULT 0,
    "obesity_level" INT DEFAULT 0,
    "fat_control_quantity" DOUBLE PRECISION DEFAULT 0,
    "weight_control_quantity" DOUBLE PRECISION DEFAULT 0,
    "muscle_control_quantity" DOUBLE PRECISION DEFAULT 0,
    "standard_body_weight" DOUBLE PRECISION DEFAULT 0,
    "ideal_weight" DOUBLE PRECISION DEFAULT 0,
    "body_cell_volume_kg" DOUBLE PRECISION DEFAULT 0,
    "extracellular_water_volume_kg" DOUBLE PRECISION DEFAULT 0,
    "intracellular_water_volume_kg" DOUBLE PRECISION DEFAULT 0,
    "left_hand_fat_mass_kg" DOUBLE PRECISION DEFAULT 0,
    "left_foot_fat_mass_kg" DOUBLE PRECISION DEFAULT 0,
    "right_hand_fat_mass_kg" DOUBLE PRECISION DEFAULT 0,
    "right_foot_fat_mass_kg" DOUBLE PRECISION DEFAULT 0,
    "trunk_fat_mass_kg" DOUBLE PRECISION DEFAULT 0,
    "left_hand_fat_rate_percent" DOUBLE PRECISION DEFAULT 0,
    "left_foot_fat_rate_percent" DOUBLE PRECISION DEFAULT 0,
    "right_hand_fat_rate_percent" DOUBLE PRECISION DEFAULT 0,
    "right_foot_fat_rate_percent" DOUBLE PRECISION DEFAULT 0,
    "trunk_fat_rate_percent" DOUBLE PRECISION DEFAULT 0,
    "left_hand_muscle_mass_kg" DOUBLE PRECISION DEFAULT 0,
    "left_foot_muscle_mass_kg" DOUBLE PRECISION DEFAULT 0,
    "right_hand_muscle_mass_kg" DOUBLE PRECISION DEFAULT 0,
    "right_foot_muscle_mass_kg" DOUBLE PRECISION DEFAULT 0,
    "trunk_muscle_mass_kg" DOUBLE PRECISION DEFAULT 0,
    "skeletal_muscle_mass_index" DOUBLE PRECISION DEFAULT 0,
    "whr" DOUBLE PRECISION DEFAULT 0,
    "left_hand_muscle_rate" DOUBLE PRECISION DEFAULT 0,
    "left_leg_muscle_rate" DOUBLE PRECISION DEFAULT 0,
    "right_hand_muscle_rate" DOUBLE PRECISION,
    "right_foot_muscle_rate" DOUBLE PRECISION DEFAULT 0,
    "trunk_muscle_rate" DOUBLE PRECISION DEFAULT 0,
    "skeletal_muscle_mass_kg" DOUBLE PRECISION DEFAULT 0,
    "screening_status" BOOL NOT NULL DEFAULT False,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "created_user_role" VARCHAR(50) DEFAULT '',
    "created_role_type" VARCHAR(50) DEFAULT '',
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_user_role" VARCHAR(50) DEFAULT '',
    "updated_role_type" VARCHAR(50) DEFAULT '',
    "deleted_at" TIMESTAMPTZ,
    "is_deleted" BOOL NOT NULL DEFAULT False,
    "school_id" BIGINT NOT NULL REFERENCES "health_passport_schools" ("school_id") ON DELETE CASCADE,
    "student_id" BIGINT NOT NULL REFERENCES "students" ("id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "idx_student_sma_school__c7920b" ON "student_smart_scale" ("school_id");
CREATE INDEX IF NOT EXISTS "idx_student_sma_student_d3c638" ON "student_smart_scale" ("student_id");
CREATE TABLE IF NOT EXISTS "parent_screening_answers" (
    "parent_answer_id" BIGSERIAL NOT NULL PRIMARY KEY,
    "question_id" BIGINT NOT NULL,
    "answer" VARCHAR(100) NOT NULL DEFAULT '',
    "notes" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "created_user_role" VARCHAR(50) DEFAULT '',
    "created_role_type" VARCHAR(50) DEFAULT '',
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_user_role" VARCHAR(50) DEFAULT '',
    "updated_role_type" VARCHAR(50) DEFAULT '',
    "deleted_at" TIMESTAMPTZ,
    "is_deleted" BOOL NOT NULL DEFAULT False,
    "parent_id" BIGINT NOT NULL REFERENCES "users_parents" ("id") ON DELETE CASCADE,
    "student_id" BIGINT NOT NULL REFERENCES "students" ("id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "idx_parent_scre_parent__a3fce3" ON "parent_screening_answers" ("parent_id");
CREATE INDEX IF NOT EXISTS "idx_parent_scre_student_3a012f" ON "parent_screening_answers" ("student_id");
CREATE TABLE IF NOT EXISTS "students_question_bank" (
    "question_id" BIGSERIAL NOT NULL PRIMARY KEY,
    "question_text" VARCHAR(255) NOT NULL DEFAULT '',
    "question_type" VARCHAR(100) NOT NULL DEFAULT '',
    "sub_domain" VARCHAR(100) NOT NULL DEFAULT '',
    "score_type" VARCHAR(50) NOT NULL DEFAULT '',
    "applicable_to_parent" BOOL NOT NULL DEFAULT False,
    "applicable_to_teacher" BOOL NOT NULL DEFAULT False,
    "grade_level" VARCHAR(100) DEFAULT '',
    "notes" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "created_user_role" VARCHAR(50) DEFAULT '',
    "created_role_type" VARCHAR(50) DEFAULT '',
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_user_role" VARCHAR(50) DEFAULT '',
    "updated_role_type" VARCHAR(50) DEFAULT '',
    "deleted_at" TIMESTAMPTZ,
    "is_deleted" BOOL NOT NULL DEFAULT False
);
CREATE TABLE IF NOT EXISTS "teacher_screening_answers" (
    "teacher_answer_id" BIGSERIAL NOT NULL PRIMARY KEY,
    "question_id" BIGINT NOT NULL,
    "notes" TEXT,
    "answer" VARCHAR(100) NOT NULL DEFAULT '',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "created_user_role" VARCHAR(50) DEFAULT '',
    "created_role_type" VARCHAR(50) DEFAULT '',
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" BIGINT,
    "updated_user_role" VARCHAR(50) DEFAULT '',
    "updated_role_type" VARCHAR(50) DEFAULT '',
    "deleted_at" TIMESTAMPTZ,
    "is_deleted" BOOL NOT NULL DEFAULT False,
    "student_id" BIGINT NOT NULL REFERENCES "students" ("id") ON DELETE CASCADE,
    "teacher_id" BIGINT NOT NULL REFERENCES "users_school_staff" ("id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "idx_teacher_scr_student_f9d387" ON "teacher_screening_answers" ("student_id");
CREATE INDEX IF NOT EXISTS "idx_teacher_scr_teacher_4594a4" ON "teacher_screening_answers" ("teacher_id");
CREATE TABLE IF NOT EXISTS "aerich" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "version" VARCHAR(255) NOT NULL,
    "app" VARCHAR(100) NOT NULL,
    "content" JSONB NOT NULL
);
CREATE TABLE IF NOT EXISTS "health_passport_parent_children" (
    "student_id" BIGINT NOT NULL REFERENCES "users_parents" ("id") ON DELETE CASCADE,
    "parent_id" BIGINT NOT NULL REFERENCES "students" ("id") ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "uidx_health_pass_student_a6c12a" ON "health_passport_parent_children" ("student_id", "parent_id");"""


async def downgrade(db: BaseDBAsyncClient) -> str:
    return """
        """
